### ISSUE TITLE
xraylib conda package for Windows?

### ISSUE THREAD

**Issue by tschoonj** [conda-forge/xraylib-feedstock#4]
@tacaswell @licode @ericdill 

I managed to create a working python xraylib plugin within my Windows Anaconda3 installation, only using tools that were available in the default channel. Just the SWIG based plugin though, the Cython one segfaults when it's being loaded.

I assume this means that it should be possible to generate a conda package for Windows now, but I am not really sure how to get started with this. For example I need to use a lot of additional Windows-only packages (like m2w64-gcc, m2-bash and m2-libtool), but it's not clear to me how to add these to recipe/meta.yaml in a platform-dependent manner.

Any advice here would be greatly appreciated!

Thanks,

Tom

**Comment by tschoonj** [comment]
Another thing is that I will need to apply a patch to the currently stable tarball for this to work: is there an entry I can add to recipe/meta.yaml for this or do I need to do this in bld.bat myself using wget/curl and patch?

**Comment by ericdill** [comment]
@tschoonj so IIUC the two questions are how to include windows-only-dependencies and how to apply a windows-only-patch. For the windows-only-dependencies, you can add them to the requirements/build section and the requirements/run section, depending on when they are needed, by adding what is called a "selector", like this: https://github.com/conda-forge/xraylib-feedstock/blob/master/recipe/meta.yaml#L14. All selectors can be found here: https://conda.io/docs/building/meta-yaml.html#preprocessing-selectors

For the windows-only-patch, add a patch file to the `recipe/` folder of the feedstock, call them out in the recipe like this: https://conda.io/docs/building/meta-yaml.html#patches and use the windows selector (`#  [win]`) on that line and the `patches:` line too.

**Comment by tschoonj** [comment]
Thanks Eric for the information

This will take me some time to get right...

**Comment by ericdill** [comment]
Indeed. It is a non-trivial process. Report back with any issues and I'll see if I can help point you in the right direction
